apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-gateway-grpc-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.0"
  POD_NAME: "go-gateway-grpc.k8"
  PORT: "6000"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  ENV: "dev"

  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"
  USE_STDOUT_TRACER_EXPORTER: "false"
  USE_OTLP_COLLECTOR: "true" 
  AWS_CLOUDWATCH_LOG_GROUP_NAMES: "/dock/eks/eks-arch-01"

  NAME_SERVICE_01: "go-account"
  URL_SERVICE_01: "https://vpce.global.dev.caradhras.io/pv"
  METHOD_SERVICE_01: "GET"
  X_APIGW_API_ID_SERVICE_01: "129t4y8eoj"